#!/bin/bash

clear
echo "======================================"
echo "       VPS PORT FORWARDER"
echo "======================================"
echo

# Auto detect public IP
YOUR_IP=$(curl -4 -s https://ifconfig.me)

if [[ -z "$YOUR_IP" ]]; then
    echo "❌ VPS public IP detect nahi hua."
    exit 1
fi

echo "VPS IP: $YOUR_IP"
echo

read -p "Target VPS IP: " TARGET_IP
read -p "Source Port: " SOURCE_PORT
read -p "Target Port: " TARGET_PORT

# Enable IP forwarding
sysctl -w net.ipv4.ip_forward=1 >/dev/null

# TCP
iptables -t nat -A PREROUTING \
    -d "$YOUR_IP" \
    -p tcp \
    --dport "$SOURCE_PORT" \
    -j DNAT \
    --to-destination "$TARGET_IP:$TARGET_PORT"

# UDP
iptables -t nat -A PREROUTING \
    -d "$YOUR_IP" \
    -p udp \
    --dport "$SOURCE_PORT" \
    -j DNAT \
    --to-destination "$TARGET_IP:$TARGET_PORT"

# NAT
iptables -t nat -A POSTROUTING \
    -p tcp \
    -d "$TARGET_IP" \
    --dport "$TARGET_PORT" \
    -j MASQUERADE

iptables -t nat -A POSTROUTING \
    -p udp \
    -d "$TARGET_IP" \
    --dport "$TARGET_PORT" \
    -j MASQUERADE

echo
echo "======================================"
echo "✅ FORWARDING ENABLED"
echo "======================================"
echo
echo "$YOUR_IP:$SOURCE_PORT"
echo "        ↓"
echo "$TARGET_IP:$TARGET_PORT"
echo
